// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Facebook_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IFacebook_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaFacebook_Detail0 property.
        /// </summary>
		bool HasNextpanoramaFacebook_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaFacebook_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaFacebook_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the ShareFacebook_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareFacebook_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartFacebook_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartFacebook_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceFacebook_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceFacebook_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaFacebook_Detail0 command.
        /// </summary>
		ICommand NextpanoramaFacebook_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaFacebook_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaFacebook_Detail0 { get; }

	}
}
