// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Forum_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IForum_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaForum_Detail0 property.
        /// </summary>
		bool HasNextpanoramaForum_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaForum_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaForum_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the ShareForum_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareForum_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartForum_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartForum_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceForum_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceForum_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaForum_Detail0 command.
        /// </summary>
		ICommand NextpanoramaForum_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaForum_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaForum_Detail0 { get; }

	}
}
