// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Web_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IWeb_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaWeb_Detail0 property.
        /// </summary>
		bool HasNextpanoramaWeb_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaWeb_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaWeb_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the ShareWeb_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareWeb_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartWeb_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartWeb_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceWeb_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceWeb_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaWeb_Detail0 command.
        /// </summary>
		ICommand NextpanoramaWeb_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaWeb_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaWeb_Detail0 { get; }

	}
}
