// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// YouTube_DetailVideos ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IYouTube_DetailVideosViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentYouTubeVideo property.
        /// </summary>
		EntitiesBase.YouTubeVideo CurrentYouTubeVideo { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaYouTube_DetailVideos0 property.
        /// </summary>
		bool HasNextpanoramaYouTube_DetailVideos0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaYouTube_DetailVideos0 property.
        /// </summary>
		bool HasPreviouspanoramaYouTube_DetailVideos0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechYouTube_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechYouTube_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareYouTube_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand ShareYouTube_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartYouTube_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand PinToStartYouTube_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceYouTube_DetailVideosStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceYouTube_DetailVideosStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaYouTube_DetailVideos0 command.
        /// </summary>
		ICommand NextpanoramaYouTube_DetailVideos0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaYouTube_DetailVideos0 command.
        /// </summary>
		ICommand PreviouspanoramaYouTube_DetailVideos0 { get; }

	}
}
