// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Forum_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class Forum_DetailViewModel : ViewModelsBase.VMBase, IViewModels.IForum_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.Forum_Forum _forum_Forum;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Forum_DetailViewModel" /> class.
        /// </summary>
        /// <param name="forum_Forum">The Forum_ Forum.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public Forum_DetailViewModel(Repositories.Forum_Forum forum_Forum, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_forum_Forum = forum_Forum;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }
	
		private bool _hasNextpanoramaForum_Detail0;

        /// <summary>
        /// HasNextpanoramaForum_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramaForum_Detail0
        {
            get
            {
				return _hasNextpanoramaForum_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramaForum_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramaForum_Detail0;

        /// <summary>
        /// HasPreviouspanoramaForum_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramaForum_Detail0
        {
            get
            {
				return _hasPreviouspanoramaForum_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramaForum_Detail0, value);
            }
        }

        /// <summary>
        /// Delegate method for the ShareForum_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareForum_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentRssSearchResult.Content, CurrentRssSearchResult.PublishDate.ToString(), CurrentRssSearchResult.FeedUrl, "");
        }
		

        private ICommand _shareForum_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareForum_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareForum_DetailStaticControlCommand
        {
            get { return _shareForum_DetailStaticControlCommand = _shareForum_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(ShareForum_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartForum_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartForum_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.IForum_DetailViewModel), CreateTileInfoForum_DetailStaticControl());
        }
		

        private ICommand _pinToStartForum_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartForum_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartForum_DetailStaticControlCommand
        {
            get { return _pinToStartForum_DetailStaticControlCommand = _pinToStartForum_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartForum_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceForum_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourceForum_DetailStaticControlCommandDelegate() 
        {
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourceForum_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceForum_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceForum_DetailStaticControlCommand
        {
            get { return _goToSourceForum_DetailStaticControlCommand = _goToSourceForum_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourceForum_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the NextpanoramaForum_Detail0 command.
        /// </summary>
        public async void NextpanoramaForum_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var next = await  _forum_Forum.Next(CurrentRssSearchResult);

			if(next != null)
				CurrentRssSearchResult = next;

			RefreshHasPrevNext();
        }
		
		
        private bool _loadingCurrentRssSearchResult;
		
        public bool LoadingCurrentRssSearchResult
        {
            get { return _loadingCurrentRssSearchResult; }
            set { SetProperty(ref _loadingCurrentRssSearchResult, value); }
        }

        private ICommand _nextpanoramaForum_Detail0;

        /// <summary>
        /// Gets the NextpanoramaForum_Detail0 command.
        /// </summary>
        public ICommand NextpanoramaForum_Detail0
        {
            get { return _nextpanoramaForum_Detail0 = _nextpanoramaForum_Detail0 ?? new ViewModelsBase.DelegateCommand(NextpanoramaForum_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the PreviouspanoramaForum_Detail0 command.
        /// </summary>
        public async void PreviouspanoramaForum_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var prev = await  _forum_Forum.Previous(CurrentRssSearchResult);

			if(prev != null)
				CurrentRssSearchResult = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramaForum_Detail0;

        /// <summary>
        /// Gets the PreviouspanoramaForum_Detail0 command.
        /// </summary>
        public ICommand PreviouspanoramaForum_Detail0
        {
            get { return _previouspanoramaForum_Detail0 = _previouspanoramaForum_Detail0 ?? new ViewModelsBase.DelegateCommand(PreviouspanoramaForum_Detail0Delegate); }
        }

        private async void RefreshHasPrevNext()
        {
            HasPreviouspanoramaForum_Detail0 = await _forum_Forum.HasPrevious(CurrentRssSearchResult);
			HasNextpanoramaForum_Detail0 = await _forum_Forum.HasNext(CurrentRssSearchResult);
			LoadingCurrentRssSearchResult = false;
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the Forum_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoForum_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Content,
                BackTitle = CurrentRssSearchResult.Content,
                BackContent = CurrentRssSearchResult.PublishDate.ToString(),
                Count = 0,
                BackgroundImagePath = string.Empty,
                BackBackgroundImagePath = string.Empty,
                LogoPath = "Logo-e5fdb3ff-dfbe-482b-8e55-b7902363885e.png"
            };
            return tileInfo;
        }
    }
}
